---
title: 'Question 3: Tennis'
author: "Andrew Hyde"
date: '2022-06-17'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = FALSE, warning = FALSE)

library(tidyverse)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))

# READ in multiple csv files
df_tennis = data_collater(data_directory = "data/Tennis/")

```

Nadal vs Djokovic: Aces and Doubles Faults in Grand Slam Finals

```{r}
graph_q3.1a_func(df_data = df_q3.1a_data,
                title = "Djokovic: Consistency of Serve in Winning Grand Slam Finals ",
                subtitle = "",
                caption = " ",
                xlabel = "Grand Slam Finals",
                ylabel = "Number Aces or Faults")

graph_q3.1b_func(df_data = df_q3.1b_data,
                title = "Nadal: Consistency of Serve in Winning Grand Slam Finals ",
                subtitle = "",
                caption = " ",
                xlabel = "Grand Slam Finals",
                ylabel = "Number Aces or Faults")
```


```{r}

graph_q3.2_func(df_data = df_q3.2_data,
                title = "Percentage of 1st Serves In: Gland Slam vs Masters 1000s ",
                subtitle = "Plot Comparing 1st Serve Percentage for All Players when winning matches (1990 - 2022)",
                caption = " ",
                xlabel = "Year",
                ylabel = "Percentage of 1st Serve In (%)")



```

```{r}
Q3_table_func(df_data)
```

